//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.11 at 03:21:48 PM ART 
//


package dao;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XMLEraseSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLEraseSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date" type="{}XMLDateRestriction" minOccurs="0"/>
 *         &lt;element name="sender" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="header-pattern" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="content-type" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="size-bytes" type="{}XMLSizeRestriction" minOccurs="0"/>
 *         &lt;element name="structure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLEraseSettings", propOrder = {
    "date",
    "sender",
    "headerPattern",
    "contentType",
    "sizeBytes",
    "structure"
})
public class XMLEraseSettings {

    protected XMLDateRestriction date;
    protected List<String> sender;
    @XmlElement(name = "header-pattern")
    protected List<String> headerPattern;
    @XmlElement(name = "content-type")
    protected List<String> contentType;
    @XmlElement(name = "size-bytes")
    protected XMLSizeRestriction sizeBytes;
    @XmlElement(required = true)
    protected String structure;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLDateRestriction }
     *     
     */
    public XMLDateRestriction getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLDateRestriction }
     *     
     */
    public void setDate(XMLDateRestriction value) {
        this.date = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sender property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSender().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSender() {
        if (sender == null) {
            sender = new ArrayList<String>();
        }
        return this.sender;
    }

    /**
     * Gets the value of the headerPattern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headerPattern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaderPattern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHeaderPattern() {
        if (headerPattern == null) {
            headerPattern = new ArrayList<String>();
        }
        return this.headerPattern;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContentType() {
        if (contentType == null) {
            contentType = new ArrayList<String>();
        }
        return this.contentType;
    }

    /**
     * Gets the value of the sizeBytes property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSizeRestriction }
     *     
     */
    public XMLSizeRestriction getSizeBytes() {
        return sizeBytes;
    }

    /**
     * Sets the value of the sizeBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSizeRestriction }
     *     
     */
    public void setSizeBytes(XMLSizeRestriction value) {
        this.sizeBytes = value;
    }

    /**
     * Gets the value of the structure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStructure() {
        return structure;
    }

    /**
     * Sets the value of the structure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStructure(String value) {
        this.structure = value;
    }

}
