//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.11 at 03:21:48 PM ART 
//


package dao;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XMLSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user" type="{}XMLUser" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="blacklist" type="{}XMLIPBlacklist"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLSettings", propOrder = {
    "user",
    "blacklist"
})
public class XMLSettings {

    protected List<XMLUser> user;
    @XmlElement(required = true)
    protected XMLIPBlacklist blacklist;

    /**
     * Gets the value of the user property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the user property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLUser }
     * 
     * 
     */
    public List<XMLUser> getUser() {
        if (user == null) {
            user = new ArrayList<XMLUser>();
        }
        return this.user;
    }

    /**
     * Gets the value of the blacklist property.
     * 
     * @return
     *     possible object is
     *     {@link XMLIPBlacklist }
     *     
     */
    public XMLIPBlacklist getBlacklist() {
        return blacklist;
    }

    /**
     * Sets the value of the blacklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLIPBlacklist }
     *     
     */
    public void setBlacklist(XMLIPBlacklist value) {
        this.blacklist = value;
    }

}
