//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.12 at 01:13:42 PM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/loginLog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dao.login;
